### PR TITLE
fix: review obj-c type encoding

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
Changes to types map:
- set `B` to `_Bool`, because `@encode(_Bool) == "B" && @encode(BOOL) == "c"`
- set `t` to `__int128`, because `int128` is undeclared identifier
- set `T` to `unsigned __int128`, because `int128` is undeclared identifier
- set `?` to `void * /* unknown */`, because `undefined` is undeclared identifier
- set `^?` to `void * /* function */`, because `@encode(typeof(&main)) == "^?"` and to distinguish from `^v`
- unset `Vv`, because `@encode(oneway void) == "Vv"`

Changes to modifiers map:
- set `O` to `bycopy`, because `by` and `copy` are undeclared identifiers
- set `R` to `byref`, because `by` and `ref` are undeclared identifiers
- set `V` to `oneway`, because `one` and `way` are undeclared identifiers

Changes to decoding function:
- check types map before checking if type is pointer, this handles `""`, `"^?"`, and `"@?"`
- remove special handling for `"^?"` and `"@?"`, functions and blocks and never strongly typed

To be reviewed later:
- `"z": "size_t"`, seems invalid
- `"w": "wchar_t"`, seems invalid
- `"%": "NXAtom"`, seems invalid
- `"!": "vector"`, seems invalid and is set on both types and modifiers map
- see `/usr/include/i386/_types.h`:
  - `"c": "char"`, whether char is signed or unsigned is implementation-specific
  - integer types, size of these types are implementation-specific

### CODE REVIEW

**Comment by t0rr3sp3dr0** [comment]
Some practical examples of the changes:

```diff
diff --git a/CoreFoundation/NSArray.h b/CoreFoundation/NSArray.h
index 08cd057..22cc647 100644
--- a/CoreFoundation/NSArray.h
+++ b/CoreFoundation/NSArray.h
@@ -9,8 +9,6 @@
 #define NSArray_h
 @import Foundation;
 
-@class undefined;
-
 @interface NSArray : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
 
 @property (readonly) unsigned long long count;
@@ -114,7 +112,7 @@
 - (id)reversedArray;
 - (id)sortedArrayFromRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range options:(unsigned long long)options usingComparator:(id /* block */)comparator;
 - (id)sortedArrayUsingComparator:(id /* block */)comparator;
-- (id)sortedArrayUsingFunction:(undefined *)function context:(void *)context;
+- (id)sortedArrayUsingFunction:(void * /* function */)function context:(void *)context;
 - (id)sortedArrayUsingSelector:(SEL)selector;
 - (id)sortedArrayWithOptions:(unsigned long long)options usingComparator:(id /* block */)comparator;
 - (id)subarrayWithRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
```

```diff
diff --git a/CoreFoundation/NSConstantArray.h b/CoreFoundation/NSConstantArray.h
index f1931a7..dc2042b 100644
--- a/CoreFoundation/NSConstantArray.h
+++ b/CoreFoundation/NSConstantArray.h
@@ -22,7 +22,7 @@
 
 /* instance methods */
 - (char)_isDeallocating;
-- (void)release;
+- (oneway void)release;
 - (void)dealloc;
 - (char)_tryRetain;
 - (id)autorelease;
```

```diff
diff --git a/Foundation/NSSpellServer.h b/Foundation/NSSpellServer.h
index f12b9b8..1b3d4c4 100644
--- a/Foundation/NSSpellServer.h
+++ b/Foundation/NSSpellServer.h
@@ -9,7 +9,6 @@
 #define NSSpellServer_h
 @import Foundation;
 
-@class by copy id;
 @protocol NSSpellServerDelegate;
 
 @interface NSSpellServer : NSObject {
@@ -27,35 +26,35 @@
 - (void)dealloc;
 - (void)run;
 - (id)dictionaryInfo:(id)info;
-- (by copy id)_stringForInputString:(in by copy id)string language:(in by copy id)language;
+- (bycopy id)_stringForInputString:(in bycopy id)string language:(in bycopy id)language;
```

**Comment by blacktop** [comment]
It looks like we colided, I prefer your cleaner solution, can you please fix the conflicts but choose your solution.

**Comment by blacktop** [comment]
Please also take a look at how I fixed `typeSpecifiers` they appear to be applied in reverse order than the rest of the types.

So it should be `bycopy in id` NOT `in bycopy id` etc

**Comment by blacktop** [comment]
With respects to NXAtom I found this https://gist.github.com/CodaFi/559cb6102032d6dd433b

Which is why I changed `NXAtom` to `const char *` (which is a weird type because there's also a `const` type specifier.  However, that might also be why it fell out of use?

**Comment by blacktop** [comment]
> With respects to NXAtom I found this https://gist.github.com/CodaFi/559cb6102032d6dd433b
> 
> Which is why I changed `NXAtom` to `const char *` (which is a weird type because there's also a `const` type specifier. However, that might also be why it fell out of use?

Your GCC find might be much more relevant.

**Comment by t0rr3sp3dr0** [comment]
This is panicking here:

```go
	if spec, ok := typeSpecifiers[string(encType[0])]; ok { // TODO: can there be more than 2 specifiers?
 		if spec2, ok := typeSpecifiers[string(encType[1])]; ok {
 			return spec2 + " " + spec + " " + decodeType(encType[2:])
 		}
 		return spec + " " + decodeType(encType[1:])
 	}
```

```console
% ipsw cd ./dyld_shared_cache_x86_64h Foundation --headers
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/blacktop/go-macho/types/objc.decodeType({0x10ee22448, 0x1})
	github.com/blacktop/go-macho/types/objc/type_encoding.go:307 +0x525
github.com/blacktop/go-macho/types/objc.decodeStructOrUnion({0xc00082e301?, 0x2d7?}, {0x10db09531, 0x6})
	github.com/blacktop/go-macho/types/objc/type_encoding.go:395 +0x5e5
github.com/blacktop/go-macho/types/objc.decodeStructure(...)
	github.com/blacktop/go-macho/types/objc/type_encoding.go:353
github.com/blacktop/go-macho/types/objc.decodeType({0xc00082e300, 0x2d7})
	github.com/blacktop/go-macho/types/objc/type_encoding.go:330 +0x61e
github.com/blacktop/go-macho/types/objc.getIVarType({0xc00082e300?, 0x10d72081c?})
	github.com/blacktop/go-macho/types/objc/type_encoding.go:260 +0xc9
github.com/blacktop/go-macho/types/objc.(*Ivar).dump(0xc026c68600, 0x20?, 0xf0?)
	github.com/blacktop/go-macho/types/objc/objc.go:453 +0x138
github.com/blacktop/go-macho/types/objc.(*Ivar).Verbose(...)
	github.com/blacktop/go-macho/types/objc/objc.go:467
github.com/blacktop/ipsw/internal/commands/macho.(*ObjC).processForwardDeclarations(0xc00080d800, 0xc0006f4780)
	github.com/blacktop/ipsw/internal/commands/macho/objc.go:982 +0x18bd
github.com/blacktop/ipsw/internal/commands/macho.(*ObjC).Headers.func1(0xc0006f4780)
	github.com/blacktop/ipsw/internal/commands/macho/objc.go:494 +0x165
github.com/blacktop/ipsw/internal/commands/macho.(*ObjC).Headers(0xc00080d800)
	github.com/blacktop/ipsw/internal/commands/macho/objc.go:665 +0x72
github.com/blacktop/ipsw/cmd/ipsw/cmd.init.func22(0xc0007f3a00?, {0xc000662210, 0x2, 0x10db0555f?})
	github.com/blacktop/ipsw/cmd/ipsw/cmd/class_dump.go:241 +0xeac
github.com/spf13/cobra.(*Command).execute(0x10ed986c0, {0xc0006621b0, 0x3, 0x3})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x10ed989a0)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
	github.com/blacktop/ipsw/cmd/ipsw/cmd/root.go:67 +0x1a
main.main()
	github.com/blacktop/ipsw/cmd/ipsw/main.go:27 +0xf
```

Should I revert?

**Comment by blacktop** [comment]
> This is panicking here:
> 
> ```go
> 	if spec, ok := typeSpecifiers[string(encType[0])]; ok { // TODO: can there be more than 2 specifiers?
>  		if spec2, ok := typeSpecifiers[string(encType[1])]; ok {
>  			return spec2 + " " + spec + " " + decodeType(encType[2:])
>  		}
>  		return spec + " " + decodeType(encType[1:])
>  	}
> ```
> 
>  ```
> % ipsw cd ./dyld_shared_cache_x86_64h Foundation --headers
> panic: runtime error: index out of range [1] with length 1
> 
> goroutine 1 [running]:
> github.com/blacktop/go-macho/types/objc.decodeType({0x10ee22448, 0x1})
> 	github.com/blacktop/go-macho/types/objc/type_encoding.go:307 +0x525
> github.com/blacktop/go-macho/types/objc.decodeStructOrUnion({0xc00082e301?, 0x2d7?}, {0x10db09531, 0x6})
> 	github.com/blacktop/go-macho/types/objc/type_encoding.go:395 +0x5e5
> github.com/blacktop/go-macho/types/objc.decodeStructure(...)
> 	github.com/blacktop/go-macho/types/objc/type_encoding.go:353
> github.com/blacktop/go-macho/types/objc.decodeType({0xc00082e300, 0x2d7})
> 	github.com/blacktop/go-macho/types/objc/type_encoding.go:330 +0x61e
> github.com/blacktop/go-macho/types/objc.getIVarType({0xc00082e300?, 0x10d72081c?})
> 	github.com/blacktop/go-macho/types/objc/type_encoding.go:260 +0xc9
> github.com/blacktop/go-macho/types/objc.(*Ivar).dump(0xc026c68600, 0x20?, 0xf0?)
> 	github.com/blacktop/go-macho/types/objc/objc.go:453 +0x138
> github.com/blacktop/go-macho/types/objc.(*Ivar).Verbose(...)
> 	github.com/blacktop/go-macho/types/objc/objc.go:467
> github.com/blacktop/ipsw/internal/commands/macho.(*ObjC).processForwardDeclarations(0xc00080d800, 0xc0006f4780)
> 	github.com/blacktop/ipsw/internal/commands/macho/objc.go:982 +0x18bd
> github.com/blacktop/ipsw/internal/commands/macho.(*ObjC).Headers.func1(0xc0006f4780)
> 	github.com/blacktop/ipsw/internal/commands/macho/objc.go:494 +0x165
> github.com/blacktop/ipsw/internal/commands/macho.(*ObjC).Headers(0xc00080d800)
> 	github.com/blacktop/ipsw/internal/commands/macho/objc.go:665 +0x72
> github.com/blacktop/ipsw/cmd/ipsw/cmd.init.func22(0xc0007f3a00?, {0xc000662210, 0x2, 0x10db0555f?})
> 	github.com/blacktop/ipsw/cmd/ipsw/cmd/class_dump.go:241 +0xeac
> github.com/spf13/cobra.(*Command).execute(0x10ed986c0, {0xc0006621b0, 0x3, 0x3})
> 	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
> github.com/spf13/cobra.(*Command).ExecuteC(0x10ed989a0)
> 	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
> github.com/spf13/cobra.(*Command).Execute(...)
> 	github.com/spf13/cobra@v1.8.0/command.go:1039
> github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
> 	github.com/blacktop/ipsw/cmd/ipsw/cmd/root.go:67 +0x1a
> main.main()
> 	github.com/blacktop/ipsw/cmd/ipsw/main.go:27 +0xf
> ```
> 
> Should I revert?

eh it's still correct that it's a reverse order, recursive thing.  It prob just needs a length check for now?

**Comment by t0rr3sp3dr0** [comment]
I think it was my rebase.

**Comment by t0rr3sp3dr0** [comment]
Fixing here

**Comment by t0rr3sp3dr0** [comment]
Done

**Comment by blacktop** [comment]
LGTM 👍

**Pull request merged**
